### ISSUE TITLE
Requested documentation update: if scutil --nc list returns empty list of VPN endpoints, edit the config and resave

### ISSUE THREAD

**Issue by snrkl** [Chrede88/alfred-wireguard#4]
Workflow was exiting silently and not funcitoning - troubleshooting showed
```
$ scutil --nc list
Available network connection services in the current set (*=enabled):
```

System:

**MacOS** 
Ventura 13.3.1 (a) (22E772610a

**Wireguard.app** 
App version: 1.0.16 (27)
Go backend version: 1e2c3e5a

If you open and save the configs from the wireguard.app, ```scutil --nc list ``` will work again, and the Alfred workflow functions as designed
```
scutil --nc list
Available network connection services in the current set (*=enabled):
* (Disconnected)   REDACTED VPN (com.wireguard.macos) "vpn.example.com"                   [VPN:com.wireguard.macos]
* (Disconnected)   REDACTED VPN (com.wireguard.macos) "vpn.example.org"                  [VPN:com.wireguard.macos]
```

**Comment by chrede88** [comment]
This is really not an issue with the workflow, but an issue with the wireguard app! I've just released a new version (v1.1.3). The workflow will now output a text "No VPN's found!", if `scutil --nc list` doesn't return anything. This mitigates the silent exit.
